# Generated by Django 3.2.21 on 2023-09-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('skincolor', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=50)),
                ('isdisabled', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='images')),
                ('ishavingmadness', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('dateofmissing', models.CharField(max_length=50)),
                ('locationofmissing', models.CharField(max_length=50)),
                ('locationofmoles', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'missingpersons',
            },
        ),
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('recordeddate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
